### ISSUE TITLE
vim.bo. option setting method not working

### ISSUE THREAD

**Issue by GaetanLepage** [ojroques/dotfiles#6]
Dear Olivier,

I noticed that you are using the `vim.bo.smartindent = true` syntax to set the buffer local options.
However this doesn't work for me (and for other people apparently: (https://github.com/neovim/neovim/issues/12978).

Does it work for you ?

Thanks in advance !

**Comment by ojroques** [comment]
Bonsoir :)
 
Yes I did struggle to get expandtab / smarttab working. I was not aware of the issue in the Neovim repo at the time but it's likely related.

What I noticed is that you need to set both global and local options for expandtab and the others to work as intended:
```
vim.o.smartindent = true
vim.bo.smartindent = true
```

So I've written a helper function which sets both scopes for all options: https://github.com/ojroques/dotfiles/blob/9fb051dc1bf1075c727386ba70bb4ec31f7880ba/nvim/init.lua#L6 https://github.com/ojroques/dotfiles/blob/9fb051dc1bf1075c727386ba70bb4ec31f7880ba/nvim/init.lua#L14-L17

It's not elegant but so far it has worked for me:
```
nvim --headless -u NONE -c "lua vim.o.smartindent=true" -c "lua vim.bo.smartindent=true" -c "set smartindent?" -c ":e test" -c "set smartindent?" -c "exit"
smartindent
smartindent
```

**Comment by GaetanLepage** [comment]
Ok I didn't know this technique !
On my side I used `vim.cmd('set smartindent')` waiting for the patch.
:)
